apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Updated to latest version"
  name: nginx-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app_runtime_stage: staging
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  minReadySeconds: 5
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app_runtime_stage: staging
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80