apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app_runtime_stage: staging
  template:
    metadata:
      labels:
        app_runtime_stage: staging
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80