apiVersion: v1
kind: apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
  type: front-end
spec:
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-containers
          image: nginx
  replicas: 3
