apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: mya
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec: 
      containers:
      - name: nginx-container
        image: nginx
      tolerations:
      - key: "app"
        operator: "Equal"
        value: blue
        effect: NoSchedule
  replicas: 3
  selector:
    matchLabels:
      app: myapp
        
